spring.application.name=financial_api

# H2 DATABASE
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger
springdoc.swagger-ui.path=/my-ui.html
springdoc.api-docs.path=/my-api-docs

# Security
spring.security.user.name=xavierBank
spring.security.user.password=test123

logging.level.org.springframework.security=DEBUG

